-- select prod_name, prod_id, prod_price from products;
-- select prod_name from products;
-- select * from products;
-- select vend_id from products;
-- select distinct vend_id from products;
-- select distinct vend_id, prod_price from products;
-- select vend_id, prod_price from products;
-- select prod_name from products limit 5;
-- select prod_name from products limit 5 offset 5;
-- select prod_name from products limit 1 offset 1;
-- select prod_name from products limit 4 offset 3;
-- select prod_name from products limit 3, 4;
-- 注释 # -- /* */
-- select cust_id from customers;
-- select distinct prod_id from orderitems; -- limit 7;
-- select * from customers;
-- select cust_id from customers;